# ============================================
# Seal Security Configuration
# Defines vulnerability remediation rules
# ============================================

meta:
  schema-version: 0.1.0
  description: "ASP.NET Deserialization Demo - Vulnerability Remediation Config"

projects:
  # Main application project
  seal-docker-demo-app:
    description: "ASP.NET 7 Razor Pages demo with vulnerable dependencies"
    targets:
      - AppDemo.csproj
    manager:
      ecosystem: nuget
      name: nuget
    
    # Package vulnerability overrides
    overrides:
      # Replace vulnerable Newtonsoft.Json with Seal's patched version
      Newtonsoft.Json:
        "10.0.3":
          use: "10.0.3-sp1"
          reason: "Fixes CVE-2024-21907 (Stack overflow DoS vulnerability)"
          
      # Additional packages can be configured here as needed
      # Example:
      # "Microsoft.AspNetCore.App":
      #   "7.0.0":
      #     use: "7.0.20"
      #     reason: "Security updates for ASP.NET Core"

# Global settings
settings:
  # Prefer sealed packages over version upgrades when available
  prefer_sealed_packages: true
  
  # Upload scan results to Seal platform for tracking
  upload_results: true
  
  # Fail build if critical vulnerabilities cannot be fixed
  fail_on_unfixable_critical: false